# Generated by Django 5.1.1 on 2024-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_rent', models.CharField(max_length=10)),
                ('days', models.CharField(max_length=3)),
                ('order_date', models.CharField(max_length=50)),
                ('dealer_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=50)),
                ('vehicle_image', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('vehicle_id', models.IntegerField()),
                ('capacity', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('phoneno', models.BigIntegerField(unique=True)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('secure_question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=45)),
                ('earnings', models.IntegerField(default=0)),
                ('images', models.CharField(default='user.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=2)),
                ('is_available', models.BooleanField(default=True)),
                ('rent', models.CharField(max_length=10)),
                ('dealer_id', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
